### PR TITLE
batch JSON-RPC requests

### PR DESCRIPTION
**Pull request by kranthicodes**
## Summary 
batched JSON-RPC requests in the background to increase performance of indexing just like it was implemented in ord for bitcoin. I was able to finish indexing of ~2400000 blocks in 45mins. Before this PR, indexing was slow.

### CODE REVIEW

**Comment by kranthicodes** [comment]
@ynohtna92, Can you review please this and let me know if you agree with the proposed changes too?

**Comment by Cortexelus** [comment]
whoa this indexes way faster. thanks sai!

I did `git checkout` for this pull request, recompiled, and ran the indexer (from a previous checkpoint which was up to ~2017). It was super fast. But just before the very end I got this error:

```
[2023-02-22T20:45:31Z INFO  ord::index::updater] Wrote 0 sat ranges from 0 outputs in 0 ms
[2023-02-22T20:45:31Z INFO  ord::index::updater] Block 2424427 at 2023-02-18 03:33:54 UTC with 0 transactions…
[2023-02-22T20:45:31Z INFO  ord::index::updater] Wrote 0 sat ranges from 0 outputs in 0 ms
[2023-02-22T20:45:31Z INFO  ord::index::updater] Block 2424428 at 2023-02-18 03:34:34 UTC with 0 transactions…
[2023-02-22T20:45:31Z INFO  ord::index::updater] Wrote 0 sat ranges from 0 outputs in 0 ms
[2023-02-22T20:45:31Z INFO  ord::index::updater] Block 
`2424429 at 2023-02-18 03:46:26 UTC with 607 transactions…
Failed deserialize
[2023-02-22T20:45:33Z ERROR ord::index::updater] Couldn't receive txs Result for batched JSON-RPC response not valid bitcoin tx: parse failed: data not consumed entirely when explicitly deserializing
[2023-02-22T20:45:33Z INFO  ord::index::updater] Block receiver disconnected: sending on a closed channel
error: failed to get transaction for 1deb0e52f753ab6cdf85f90e2aae58de3d5c23c1a4de4041b3654873e10a7864
```

but then checking out origin/master branch again it was able to finish from `2023-02-18` at the slower speed.

Not sure if the error was a result of a bug in the PR, or because of the way i was switching branches

**Comment by ynohtna92** [comment]
@kranthicodes I'll test this out today? How is this different to the Ord batch tx on BTC? Did you have to do any additional changes?

**Comment by ynohtna92** [comment]
Closing, merged from casey/ord https://github.com/ynohtna92/ord-litecoin/commit/f8533c766dec985f4a64f73b0ee073b4c32b03cc

**Comment by pluto2sun** [comment]
> whoa this indexes way faster. thanks sai!
> 
> I did `git checkout` for this pull request, recompiled, and ran the indexer (from a previous checkpoint which was up to ~2017). It was super fast. But just before the very end I got this error:
> 
> ```
> [2023-02-22T20:45:31Z INFO  ord::index::updater] Wrote 0 sat ranges from 0 outputs in 0 ms
> [2023-02-22T20:45:31Z INFO  ord::index::updater] Block 2424427 at 2023-02-18 03:33:54 UTC with 0 transactions…
> [2023-02-22T20:45:31Z INFO  ord::index::updater] Wrote 0 sat ranges from 0 outputs in 0 ms
> [2023-02-22T20:45:31Z INFO  ord::index::updater] Block 2424428 at 2023-02-18 03:34:34 UTC with 0 transactions…
> [2023-02-22T20:45:31Z INFO  ord::index::updater] Wrote 0 sat ranges from 0 outputs in 0 ms
> [2023-02-22T20:45:31Z INFO  ord::index::updater] Block 
> `2424429 at 2023-02-18 03:46:26 UTC with 607 transactions…
> Failed deserialize
> [2023-02-22T20:45:33Z ERROR ord::index::updater] Couldn't receive txs Result for batched JSON-RPC response not valid bitcoin tx: parse failed: data not consumed entirely when explicitly deserializing
> [2023-02-22T20:45:33Z INFO  ord::index::updater] Block receiver disconnected: sending on a closed channel
> error: failed to get transaction for 1deb0e52f753ab6cdf85f90e2aae58de3d5c23c1a4de4041b3654873e10a7864
> ```
> 
> but then checking out origin/master branch again it was able to finish from `2023-02-18` at the slower speed.
> 
> Not sure if the error was a result of a bug in the PR, or because of the way i was switching branches

i met the same error like what you have posted above but i dont know how to solve it, do you have any solutions?

**Comment by ynohtna92** [comment]
> i met the same error like what you have posted above but i dont know how to solve it, do you have any solutions?

@Cortexelus @pluto2sun 
Turn on -rpcserialversion 1 on your litecoin node. This error is because mweb is half implemented in rust-litecoin... I'll get around to it eventually.

**Pull request closed without merging**
